### ISSUE TITLE
A5MP board wiring diagram & LED indicators

### ISSUE THREAD

**Issue by 3DThingy** [synthread/Klippventurer#23]
Sharing these diagrams I got from FF while diagnosing blinking lights problem while the bed is heating.

![image-1](https://github.com/synthread/Klippventurer/assets/150938507/73e04e61-3d0b-4526-b6fc-2281bd300939)
![image](https://github.com/synthread/Klippventurer/assets/150938507/8109123d-1e7d-49b1-b045-ea1e447ab801)

More about the blinking lights issue: It was never resolved. I don't think anyone has noticed or discussed this issue before, but when the bed is heating and at temp. close to the set bed temp. the relay and the LED indicator D12 will continuously turn on and off causing the light to blink..They weren't able to resolve it, but I do believe it's a firmware issue.

**Comment by The-Synthax** [comment]
Thank you for sharing. The blinking lights aren't an issue, and any noise you hear from the bed mosfet and coils is normal. This isn't a separately controlled LED for the status, it's powered directly by the bed mosfet in parallel to the bed itself when the fet is triggered. Power is controlled via PWM, so it's only ever either fully on or fully off, with temperature controlled by the amount of time it is on, also called "duty cycle". Firmware can't make it not behave this way, as there isn't any hardware onboard for controlling the bed in an analog fashion. The nozzle and fans all work this way as well.
